// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mefgxasebhdlqydrjzyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lZmd4YXNlYmhkbHF5ZHJqenlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1Njc1MjMsImV4cCI6MjA2NDE0MzUyM30.ECzsxduvgaYwM8hQQiGsr6Sf40o6tNF0t9Oj2-5OvoY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);